sudo: false
language: rust
cache: cargo

addons:
  apt:
    packages:
      - libssl-dev

rust:
  - nightly
  - beta
  - stable

before_script: |
  rustup component add rustfmt
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin
  fi

script:
  - cargo fmt -- --check
  - cargo test
  - cargo test --features serde
  - cargo test --features postgres
  - cargo test --features diesel

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --all-features --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
